title: Chuyi (Linda) Zhao
favicon: /assets/img/bocchi.ico
logo: /assets/img/mimi_Fotor.png
description: My personal webpage for sharing all my projects and experiences.

show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

email_1: zhlinda3@gmail.com
email_2: chuyi.zhao@tufts.edu
resume_link: /assets/pdf/CS.Chuyi.Zhao.pdf
blog_link: https://lindazhao.notion.site/Chuyi-s-Tech-Journey-2bffcd3c54dd4f179961db2d14ae828c
fault: /_layouts/404.html

# Github links
github:
  is_project_page: false
  owner_name: lindazha0
  owner_url: https://github.com/lindazha0
  repository_name: lindazha0.github.io
  repository_url: https://github.com/lindazha0