title: Chuyi (Linda) Zhao
logo: /assets/img/mimi_Fotor.png
description: My personal webpage for sharing all my projects and experiences.

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

email_1: zhaochy1@shanghaitech.edu.cn
email_2: zhlinda3@gmail.com
resume_link: /assets/pdf/cv_se.pdf
blog_link: https://lindazhao.notion.site/Chuyi-s-Tech-Journey-2bffcd3c54dd4f179961db2d14ae828c
fault: /_layouts/404.html